stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: library/app:v1
      pushRemote: true
      registry: core.harbor.local
timeout: 60
notification: {}
