stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: library/app:v1
      registry: 172.22.101.111:30003
timeout: 60
notification: {}
