stages:
- name: Build
  steps:
  - runScriptConfig:
      image: docker:latest
      shellScript: |-
        docker login --username=admin --password=Harbor12345 harbor:30003
        docker build -t library/app:v1 -f ./Dockerfile .
        docker push library/app:v1
timeout: 60
notification: {}
