stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: projet/app:v1
      registry: https://172.22.101.111:30003/
timeout: 60
notification: {}
